<div id="aboutPage">

    <div class="subheader">
        <div class="title">What is Fridge to Food?</div>
    </div>

	<p>Fridge to Food is a collaborative cookbook.  It is a place to share
	recipes with other foodies.  It is a place to come to find cool new recipes
	to try, or to find recipes to make with what you have on hand.  Basically, 
	I wanted a recipe database site with certain features and couldn't find one.
	So I made one and this is it!</p>


</div>
