<div id="faq" >
	<div class="header"><div class="title">What is this place?</div></div>
	<div id="q1" class=" question">
        <p>Fridge to Food is a collaborative cookbook.  It is a place for foodies to share recipes and food photography and 
        gain reputation.  To learn more, read the <a href="<?PHP echo Zend_Registry::get('config')->hosts->home; ?>">about</a> page.</p>	
    </div>
	<div class="header"><div class="title">What is reputation?</div></div>
	<div id="q6" class=" question">
		<p>Reputation is a measure of how much the community trusts a user as cook and as a member of the community.  You
        gain reputation when recipes and photographs you posted recieve upvotes.  You lose reputation when they recieve
        down votes.  To learn more, read the <a href="<?PHP echo Zend_Registry::get('config')->hosts->home; ?>/about">about</a> page.</p>
	</div>
	<div class="header"><div class="title">What recipes may I post?</div></div>
	<div id="q1" class=" question">
		<p>Any recipe you want to.  As long as it involves food (where food can include drinks) it is welcome here.</p>
	</div>
	<div class="header"><div class="title">When can I post a recipe as mine?</div></div>
	<div id="q2" class=" question">
		<p>This is a difficult question to answer, and we will leave it largely with in your own judgement.  
		The rules of thumb we like to go by are pretty simple.</p>
		<ul>
		<li>
			<p>If you have changed two or more significant ingredients.</p>
			<p class="subtext">By "significant" we mean a major ingredient in the recipe.  Not just adding salt and pepper to taste.  Again, use your judgement on this.</p>
		</li>
		<li>
			<p>If you have significantly altered two or more steps in the process.</p>
			<p class="subtext">Again, use your own judgement on what constitutes "significant" here.</p>
		</li> 
		<li>
			<p>If you cannot remember where you found it.</p>
			<p class="subtext">You've been making it so long that you can't remember where you got it.  You've undoubtably altered it in some way.  It's yours.</p>
		</li>
		<li>
			<p>If it was passed down to you by a relative.</p>
			<p class="subtext">Unless, of course, they want to claim it as their own.</p>
		</li>
		<li>
			<p>Finally, when in doubt, make it a community recipe.</p>
			<p class="subtext">You can still share it, people can still find it, you can still get reputation from your photographs of it, but you won't get reputation from the recipe itself.</p>
		</li>
		</ul>
	</div>
	<div class="header"><div class="title">What is a community recipe?</div></div>
	<div id="q3" class=" question">
        <p>A community recipe is one which the poster did not create, but still
        wanted to share.  The poster of a community recipe still gains reputation for
        sharing it -- it takes skill to recognize a good recipe.  However, they will
        gain much less than if they created the recipe.  When posting a community
        recipe, make sure to cite the source of the recipe.	</p>
	</div>
	<div class="header"><div class="title">What images may I post?</div></div>
	<div id="q4" class=" question">
		<p >Only images that you have taken and therefore own the copyright to.  Images taken from other people or off of other websites 
		will be removed.  All reputation granted from them will be lost.</p>
	</div>
	<div class="header"><div class="title">What is a &quot;vote&quot;?</div></div>
	<div id="q5" class=" question">
		<p >A vote is a &quot;thumbs up&quot; or a &quot;thumbs down&quot;.  The votes you see for each recipe are the sum of the 
		votes up (thumbs up) minus the sum of the votes down (thumbs down).  When you are logged in and 
		viewing recipes you can choose to vote them up or vote them down.  A vote up means you really like 
		the recipe.  A vote down means you really don't like it.  When voting on recipes, you should only 
		vote for recipes you have prepared and tried.  When you vote on a recipe, you are announcing to 
		the Fridge to Food community, &quot;I tried this recipe and I loved it!&quot; Or you are saying, &quot;I tried 
		this recipe and I hated it!&quot; </p>
		<p >When browsing the image gallery you'll have a chance to give individual images an up or down vote.  
		Image votes carry a little less weight in reputation.  You can choose to vote up 
		images that really entice you to try the recipe, or ones that you feel are really representative of the 
		recipe.  Or you can choose to vote up images that you feel display both excellent cooking skills (the 
		food looks delicious) and excellent photography skills (the image is well taken).  It's all up to you really.</p>
	</div>
	<div class="header"><div class="title">What is a tag?</div></div>
	<div id="q7" class=" question">
		<p >Tags are simply another way of organizing or sorting recipes.  They can be used to denote a recipe's 
		origin or ethnic background, any allergens in the recipe, any special diets the recipe is okay for 
		or any other feature of the recipe someone might be interested in searching for. </p>
	</div>
</div>
