<div id="faq" >
	<div class="header"><div class="title">What is this place?</div></div>
	<div id="q1" class=" question">
        <p>Fridge to Food is a collaborative cookbook.  It is a place for foodies to share recipes and food photography.</p>	
    </div>
	<div class="header"><div class="title">What recipes may I post?</div></div>
	<div id="q1" class=" question">
		<p>Any recipe you want to.  As long as it involves food (where food can include drinks) it is welcome here.</p>
	</div>
	<div class="header"><div class="title">What images may I post?</div></div>
	<div id="q4" class=" question">
		<p >Only images that you have taken and therefore own the copyright to.  Images taken from other people or off of other websites 
		will be removed.</p>
	</div>
	<div class="header"><div class="title">What is a &quot;vote&quot;?</div></div>
	<div id="q5" class=" question">
		<p >A vote is a &quot;thumbs up&quot; or a &quot;thumbs down&quot;.  The votes you see for each recipe are the sum of the 
		votes up (thumbs up) minus the sum of the votes down (thumbs down).  When you are logged in and 
		viewing recipes you can choose to vote them up or vote them down.  A vote up means you really like 
		the recipe.  A vote down means you really don't like it.  When voting on recipes, you should only 
		vote for recipes you have prepared and tried.  When you vote on a recipe, you are announcing to 
		the Fridge to Food community, &quot;I tried this recipe and I loved it!&quot; Or you are saying, &quot;I tried 
		this recipe and I hated it!&quot; </p>
		<p >When browsing the image gallery you'll have a chance to give individual images an up or down vote.  
		You can choose to vote up 
		images that really entice you to try the recipe, or ones that you feel are really representative of the 
		recipe.  Or you can choose to vote up images that you feel display both excellent cooking skills (the 
		food looks delicious) and excellent photography skills (the image is well taken).  It's all up to you really.</p>
	</div>
	<div class="header"><div class="title">What is a tag?</div></div>
	<div id="q7" class=" question">
		<p >Tags are simply another way of organizing or sorting recipes.  They can be used to denote a recipe's 
		origin or ethnic background, any allergens in the recipe, any special diets the recipe is okay for 
		or any other feature of the recipe someone might be interested in searching for. </p>
	</div>
</div>
