<div id="privacy">
    <h1 >Our Privacy Policy</h1>
    <p>Information you provide privately (such as your e-mail address) will never be shared with anyone with out
    your explicit consent.  The information you have provided publicly (profile information, recipes, comments)
    will be shared on publicly on the site.  It will not be shared in any other way with out first obtaining
    your consent.</p>
</div>
