<div id="tos" >
    <h1 >Our Terms of Service</h1>
    <ol>
    <li>We are not responsible for the recipes shared on this site.  We provide the place, the users provide the content.
    We cannot gaurentee the validity of the content.</li>
    <li>Be nice to each other. We are all here for a love of food and to share that love.</li>
    <li>Post recipes you did not originate or substantially change as community recipes.  Only take credit for your 
    own work, please.</li>
    <li>The posting user retains copyright of all content posted by that user.  If the posting user removes content, 
    it will be gone.</li>
    <li>These terms of service may change.  We will notify you of any changes and give you the change to remove
    your content, if you so chose, before the changes take effect.</li>
    </ol>
</div>
    
