<div class="header" >
	<div class="title"><?php echo $this->user->getDisplayName(); ?></div>
	<div class="controls" >

		<?php if(Zend_Auth::getInstance()->hasIdentity() && Zend_Auth::getInstance()->getIdentity()->getUserID() == $this->user->getUserID()) { ?>
				<a href="/user/edit">Edit</a>
                <a href="/user/badge">Get a Badge</a>
		<?php }?>
		
	</div>
</div>
<div id="usersProfile" >
	<div id="image"  
		<?php 
			if($this->user->getProfileImage() && $this->user->getProfileImage()->fileExists()) {	
		?>
			style="background-image: url(<?PHP echo Zend_Registry::get('config')->hosts->image; ?>/medium/<?php echo $this->user->getProfileImage()->getImageID(); ?>.jpg);"
		<?php
			} 
		?>>


	</div>
	<div id="about" ><?php echo str_replace("\n", "<br>", $this->user->getAbout()); ?></div>
	<div id="info" >
        <?PHP if($this->user->getWebsiteURL() && $this->user->getWebsite()) { ?>
            <p><span class="label">Website</span><span class="value"><a href="<?PHP echo $this->user->getWebsiteURL(); ?>"><?PHP echo $this->user->getWebsite(); ?></a></span></p> 
        <?PHP } else if($this->user->getWebsite()) { ?>
            <p><span class=" label">Website</span><span class="value"><?php echo $this->user->getWebsite(); ?></span></p>
        <?PHP } else if($this->user->getWebsiteURL()) { ?>
            <p><span class=" label">Website</span><span class="value"><?php echo $this->user->getWebsiteURL(); ?></span></p>
        <?PHP } else {?>
            <p><span class=" label">Website</span><span class="value"></span></p>
        <?PHP } ?>
		<p><span class=" label">Last Seen</span><span class=" value"><?php echo $this->user->getSeen(); ?></span></p>
		<p ><span class=" label">Registered</span><span class=" value"><?php echo $this->user->getCreated(); ?></span></p>
	</div>
	
	<div class="clear"></div>
	
	<div class="header"><div class="title">ribbons earned</div></div>
	<div id="ribbons">
    <?PHP $types = array('blue', 'red', 'white', 'rainbow'); ?>
	<?PHP foreach($types as $type) { ?>
        <?PHP if(isset($this->ribbons[$type])) { ?>
            <?PHP foreach($this->ribbons[$type] as $name => $ribbon) { ?>
                <div class="ribbon-wrapper">
                    <div class="ribbon <?PHP echo $type; ?>" title="<?PHP echo $ribbon['ribbon']->getDescription(); ?>" >
                        <?PHP echo $ribbon['ribbon']->getDisplayName(); ?>
                    </div>
                    <?PHP echo ($ribbon['count'] > 1 ? 'x' . $ribbon['count']: ''); ?>
                </div>
            <?PHP } ?>
        <?PHP } ?>
	<?PHP } ?>
	</div>
	<!--  Begin recipe browsing area. -->
	<div class="tabbedHeader">
		<div class="title">
		</div>
	</div>
    <div class="header">
        <div class="title">
			browsing <?php echo $this->photos->getTotalItemCount(); ?> photos
        </div>
        <div class="controls">
			<a href="/user/profile/tab/images/id/<?php echo $this->user->getUserID(); ?>/order/votes/">Most Votes</a>
			<a href="/user/profile/tab/images/id/<?php echo $this->user->getUserID(); ?>/order/views/">Most Views</a>
			<a href="/user/profile/tab/images/id/<?php echo $this->user->getUserID(); ?>/order/newest/">Newest</a> 
        </div>
    </div>
    <?php
		$this->renderItemPager($this->photos, 'renderImageBox'); 
    ?>
</div>
